### PR TITLE
Version 1.1

### PR DESCRIPTION
**Pull request by nicolaslopezj**
This pull request tracks the process of orion 1.1

New features / fixes:

- [x] Change license to MIT.
- [x] Languages in the admin.
- [x] Changes on pages package.
- [x] New materialize theme.
- [x] Better account management.
- [x] ~~Image attribute~~.

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
@PEM-- @applocalizations can you please make write again your locale?
I changed the schema of the localization package. English and Spanish are ready, so you can use them as examples.

You can make a pull request to merge your branch into v1.1 branch or put the code in a gist.

**Comment by applocalizations** [comment]
@PEM, let's work on these things tonight.

**Comment by mraak** [comment]
Account management still needs to be done for Materialize, I only did it  for Bootstrap.

**Comment by nicolaslopezj** [comment]
I made it for materialize

**Pull request merged**
