### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by nicolaslopezj**
This pull request tracks the progress of the version 1.0

- [x] Relationships #33.
- [x] Merge all repositories into this one.
- [x] New api for entities #76.
- [x] Remove the default publication for entities #73.
- [x] Progress support for filesystem.
- [x] Separate the code into more packages.
- [x] Change the design of the admin.
- [x] Clean up the code more, so its easier for people to contribute.
- [x] ~~Change current permission system to roles #85~~ Create a better permission system.
- [x] ~~Languages for entities and dictionary #6~~ Not in scope of the proyect, first we need i18n-db for autoform.
- [x] My account tab (change password, update profile).
- [x] Create a new website.
- [ ] Write tests #77.

Previews versions will not be compatible with the new one, but I will create a upgrade guide.

I will create a new branch so people who want to help can.

Maybe I will add more. 
I want to hear you comments

### CODE REVIEW

**Comment by rwatts3** [comment]
What were your thoughts on this item. 
`
 Change the design of the admin.
`
Are you doing something from scratch or are you looking at framework based. If you're looking at framework based I like Inspinia Admin , it looks clean and would go really well. Also could leverage widgets in the admin panel for custom reports , and statistics. Maybe this could even be broken out to a completely different package or api .

**Comment by nicolaslopezj** [comment]
Hi @rwatts3, I was thinking to change it to a simple theme.
Overriding templates will be extremely easy, you will be amazed.

**Comment by rwatts3** [comment]
I am on board with that great work btw !!!

**Comment by nicolaslopezj** [comment]
You can test this branch if you want, but the api changed and I haven't made the documentation

**Comment by timfam** [comment]
Yes that's better. The goal should be to standardize so it's super easy to
create fancy admins themes. Or rather switch between themes. If one theme
does not meet my need I want to be able to click a button and swap. For
this to happen the primary admin must not be over stuffed

**Comment by rwatts3** [comment]
I will test the branch

**Comment by timfam** [comment]
@nicolaslopezj  I guess I I should wait until after one before completing my work on hierarchy menu

**Comment by rwatts3** [comment]
How do I get the branch for 1.0 working I downloaded it and for some reason it's not working.

**Comment by timfam** [comment]
I wouldn't touch that if I were you. The pages fix is a one line. Just edit
that file for and do PR if you wish

**Comment by mraak** [comment]
@nicolaslopezj Subscribed here to see when I could get involved. Looks like only after roles package will be integrated.

**Comment by rwatts3** [comment]
I see this item  Use Collection FS as the base of filesystem marked off.  Does this means it will not be supported or added to 1.0

**Comment by nicolaslopezj** [comment]
It will not be used as the base, but you can still integrate it

**Comment by rwatts3** [comment]
Ok sounds good.  I found a project that got it working pretty well.  Once 1.0 is released I will work with @timfam to get it working.  

In the meantime what is your proposed deadline or launch date for 1.0

**Comment by nicolaslopezj** [comment]
I don't know yet, but the progress right now is like 70%

**Comment by rwatts3** [comment]
Ok sounds good btw your like a machine over there progress is coming along really nice.

**Comment by nicolaslopezj** [comment]
Decided to not use ```alanning:meteor-roles``` #85, but instead create a new roles system with more features.

**Comment by timfam** [comment]
Mind sharing some of the cons of using the existing roles?

**Comment by nicolaslopezj** [comment]
Orion roles works with actions.
First we need to define actions like ```collection.posts.update```, then we create a role and attach allow and deny rules to that action.

Also orion roles has helpers, something like this
```js
var allowedCategories = orion.roles.helper('getAllowedCategories');
```
And it will return something different depending the role.

Everything else is similar to ```alanning:meteor-role```.

That package is independent to orion, so anyone could use it

**Comment by rwatts3** [comment]
I like the direction you're going with Orion Roles. 
Definitely makes since. So basically Orion Roles will fork Alanning Roles with sugar added specific to Orion.

**Comment by nicolaslopezj** [comment]
@rwatts3, its inspired on ```alanning:meteor-roles```, but its not a fork.

Also, in orion roles the roles are always global.

**Comment by timfam** [comment]
Ok sounds good don't over work yourself now, I hope you taking enough breaks?

**Comment by timfam** [comment]
@nicolaslopezj  lets integrate https://atmospherejs.com/tmeasday/publish-counts for server side counts of entitiies pages. This will come handy in admin and frontend widgets. I think this is a must have performance inclusion

**Comment by timfam** [comment]
Don't forget to update entity (now collections I suppose) to
```
Meteor.publish('entity', function(name, arg1, arg2) {
	arg1 = arg1 ? arg1 : {};
	return orion.entities[name].collection.find(arg1, arg2);
});
```
I want to rate limit my subscriptions

**Comment by timfam** [comment]
I am sure there is a more elagant way of writing this, but we need to ensureindex on _id for all collections.
```
    Meteor.startup(function(){
        entities._ensureIndex({createdBy: 1, _id: 1}, {unique: 1});
        Profiles._ensureIndex({user_id: 1});
        pages._ensureIndex({_id: 1});
    });
```
you get the idea

**Comment by nicolaslopezj** [comment]
@timtam, now collections doesn't have default publications, you have to set it up yourself. 
With index it's the same, do it the same way you would do it with normal collections

**Comment by nicolaslopezj** [comment]
I'm not sure if you need to ensure id index, with other index it will not be done automatically

**Comment by rwatts3** [comment]
We should add an about section that gives the current version of Orion.  And some information to the admin. This could go under a special group in confit or we should create a tab called settings and move config under settings.

**Comment by timfam** [comment]
So no more subs-manager dependency? For large apps good idea to eliminate "no-index" bottle neck. We can leave this out for later

**Comment by nicolaslopezj** [comment]
@rwatts3 good idea, that could be a package. 

@timfam no dependency, but it's still compatible.

**Comment by rwatts3** [comment]
@nicolaslopezj Once 1.0 is released I will add a package `orion-about`

**Comment by rwatts3** [comment]
Post 1.0 extension idea. Add the ability to have page history , and content history. 
The user will be able to create an entity or a page , and not publish it immediately. They can come back and mark it as published, but the extension I create will allow them to publish on a specific date and time.

**Comment by rwatts3** [comment]
Also with this extension they will be able to pull content from a history table, in case they accidentally remove something or want to pull content they've previously posted.

**Comment by timfam** [comment]
@rwatts3 you mean content versions and rules to managed events including schedules? Not every one is going to need versioning and I think their may be existing rules packages we can integrate, I am not too sure

**Comment by rwatts3** [comment]
Kinda , I mean if a user wants to create an entity or a page, and they want to use a previous version of the entity , they will get a dropdown that will let them prefill the entity with the previous version. 
Also did the Pages update ever get put in to remove pages from the url.

**Comment by timfam** [comment]
Why not make "create similar page" package that just clones the present entity?
I don't think the update for the url was pushed, I would say just edit that file for now, I am kinda waiting on 1.0.

**Comment by rwatts3** [comment]
Yeah same here, i've put all my side extensions on hold until 1.0

**Comment by vonwao** [comment]
Is the entities -> collections transition significant or is it pretty much a renaming?

**Comment by timfam** [comment]
Significant but a migration path maybe possible

**Comment by nicolaslopezj** [comment]
This package is what allows us to override templates easily in orion https://github.com/nicolaslopezj/reactive-templates

**Comment by rwatts3** [comment]
I will be testing this in the morning. In the meantime , I still like the idea of setting variables inside of froala editor. Such as `{{ dict 'siteName' }}` then render it once the html is parsed on the front end. I was not successful getting this to work the last time I inquired about it. It might already be possible in 1.0. 

but using  `{{ dict 'siteName' }}` and  `{{{ dict 'siteName' }}}` didn't seem to work. Any suggestions ?

**Comment by nicolaslopezj** [comment]
Here it is the roles package that orion uses now
https://github.com/nicolaslopezj/roles

**Comment by nicolaslopezj** [comment]
Hi everyone, I made a pull request on https://github.com/orionjs/example-blog/pull/7 that makes it compatible with v1.0. If you want to try this you can download that branch and add all the packages of orion v1.0 inside a folder named "packages" of the example.

Tell me what you think.

**Comment by rwatts3** [comment]
Nice.  I've been waiting for this I'll give it a go.

**Comment by rwatts3** [comment]
Attempted to use the new example blog and received this error. 

```sh
Your app is crashing. Here's the latest log.


C:\Users\rwatts\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
TypeError: Object #<Object> has no method 'listen'
    at Router.route.name (packages/orionjs:accounts/accounts.js:34:1)
    at C:\users\rwatts\desktop\example-blog\.meteor\local\build\programs\server\packages\orionjs_accounts.js:102:4
    at C:\users\rwatts\desktop\example-blog\.meteor\local\build\programs\server\packages\orionjs_accounts.js:343:3
    at C:\users\rwatts\desktop\example-blog\.meteor\local\build\programs\server\boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\rwatts\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    at C:\users\rwatts\desktop\example-blog\.meteor\local\build\programs\server\boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.

```

**Comment by nicolaslopezj** [comment]
Sorry, there was a dependency not uploaded to the packages server. Now its fixed. 
Run meteor update and try again.

**Comment by rwatts3** [comment]
Perfect the update works.  How do you get to the Orion admin panel /admin doesn't exist

**Comment by nicolaslopezj** [comment]
navigate to /admin/dictionary

**Comment by rwatts3** [comment]
Hmm I get a white screen.  Was I supposed to keep bootstrap ?

**Comment by nicolaslopezj** [comment]
yes, you should have installed bootstrap. Can I see you log (client)?

**Comment by rwatts3** [comment]
Ok , Tried to add bootstrap and it's complaining about version constraints on core. 

here is client log. 

```sh
Uncaught ReferenceError: s is not defined
lookup.js:125 Uncaught Error: No such function: isActiveRoute
```

**Comment by nicolaslopezj** [comment]
Try now please

**Comment by rwatts3** [comment]
Will do

**Comment by rwatts3** [comment]
Very Nice !!

**Comment by timfam** [comment]
Nothing working for me, I cloned -b v1.0 for both orion and packages

**Comment by nicolaslopezj** [comment]
Where are you having trouble @timfam?

**Comment by rwatts3** [comment]
Just curious are icons deprecated ? for entities

**Comment by nicolaslopezj** [comment]
By default yes, but you can override the sidebar template and implement them easily.
Did you get how to override templates?

**Comment by timfam** [comment]
By default meteor checks packages folder right or we still have to keep declaring path in ./bashrc?

**Comment by rwatts3** [comment]
@nicolaslopezj if you are referring to that reactive-templates link you sent earlier, I haven't had a chance to look at it. But if i'm not mistaken we can now easily add , and update the admin panel any way we want. So if we wanted to group entities , which we were discussing before. We can now do this with the reactive-templates.

**Comment by nicolaslopezj** [comment]
@timfam, yes it should be added automatically, but use the example-blog project because a lot of code and package name has changed.

@rwatts3 achieve that would not be a trivial task, but with reactive templates will be a lot easier. The simple theme override all the templates that the admin requires, you can override them again. Check this file for references on templates name https://github.com/orionjs/orion/blob/v1.0/packages/simple-theme/init.js

**Comment by rwatts3** [comment]
@timfam I checked out with this command. 

```sh
git clone -b v1.0 https://github.com/orionjs/example-blog
```

```sh
git clone -b v1.0 https://github.com/orionjs/core
```
the copy the packages folder from core into the root which will now be the `packages` folder.

**Be sure to remove in your `packages` file under `.meteor` the previous orion references.**
Then run 
```sh
meteor update
```
To remove the previous versions. 
Now add this list to your cleaner `packages` file. 
```sh
orionjs:accounts
orionjs:attributes
orionjs:base
orionjs:collections
orionjs:config
orionjs:core
orionjs:dictionary
orionjs:file-attribute
orionjs:filesystem
orionjs:froala
orionjs:relationships
orionjs:simple-theme
orionjs:summernote
orionjs:tabular
orionjs:s3
```

Then run this again.
```sh
meteor update
```

**Comment by rwatts3** [comment]
@nicolaslopezj 
Thank you for the reference. I'll try this later today.

**Comment by timfam** [comment]
Works great!

**Comment by rwatts3** [comment]
Are there any breaking changes for pages or can we drop pages in and go.

**Comment by nicolaslopezj** [comment]
That package its not ready yet

**Comment by rwatts3** [comment]
So I would do 

ReactiveTemplates.set('simpleThemeLogin' , 'myLogin');

**Comment by rwatts3** [comment]
How do we create new users now ?

**Comment by nicolaslopezj** [comment]
You should do 
```js
ReactiveTemplates.set('login', 'myLogin');
```

Invitations are not ready

**Comment by vonwao** [comment]
I would like to try the v1.0 branch but I'm still not clear on how to do that. I understand the "git clone -b v1.0" of core and example-blog, but where do they need to live relative to each other?  

Is there any reference I can read?  This is one downside about meteor, a lot of magic makes this hard to figure out.

**Comment by rwatts3** [comment]
See my comment from above

**Comment by vonwao** [comment]
Ok, I did read it but it didn't quite make sense to me when I first saw it.

"the copy the packages folder from core into the root which will now be the packages folder." 

Copy packages folder into which root?  I think you must mean the root of example-blog?  I will try it.

**Comment by rwatts3** [comment]
Ok give me a couple hours I will make a repository with a working copy of v1.0

**Comment by timfam** [comment]
Hi @rwatts3 I am ready to work :). Need help with the working copy?
@vonwao  pull the example blog then pull the packages too. remember -b v1.0 then move the packages folder into example blog. Meteor update then - meteor

**Comment by vonwao** [comment]
I got it working with the instructions.  Thanks!  I just needed that clarification.

**Comment by timfam** [comment]
@nicolaslopezj is s3 fully functional now? I keep get a CORS error 
```
XMLHttpRequest cannot load https://s3.amazonaws.com/****dev. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.59.103:3000' is therefore not allowed access. The response had HTTP status code 403.
```

**Comment by nicolaslopezj** [comment]
@timfam It is, but the dependency changed, check the new instructions https://github.com/Lepozepo/S3

**Comment by timfam** [comment]
@nicolaslopezj I am trying to move all files into a package and make a single click distribution . ie for event application. Outside the package the user can override templates if they wish otherwise it will be  100% package based distributions. Is it possible to define the dictionary/collections/roles from within an external package?

**Comment by rwatts3** [comment]
Yes it is.  Just make sure that your call to the collection is included within the export.  If I'm not mistaken I believe packages get loaded first so what ever you define will be available by the time the app needs to use it.  I did this with an app I created and had no issues.

**Comment by timfam** [comment]
Okay getting a few errors here. How are you enjoying v1.0?

**Comment by rwatts3** [comment]
Sorry for such a late reply was taking a Final. I actually like 1.0 alot , I think it is really simple, and I like how we can modify the admin area with reactive templates and pretty much do what ever we want. 
Did you ever have any success with the install ?

**Comment by rwatts3** [comment]
@timfam & @nicolaslopez I'm thinking we should also include in the docs or maybe in tutorials instructions and an example for customizing the admin area using the reactive templates.  

What are your thoughts.

**Comment by timfam** [comment]
Yes definitely.  I am on a trip right now and will ping once I am settled
in. Btw I am fixing the etherpad so we can collaborate better .

**Comment by nicolaslopezj** [comment]
Documentation will be moved to ```/docs```

**Comment by timfam** [comment]
@nicolaslopezj  you are the best !!!

**Comment by timfam** [comment]
```Template "collectionspostscreate" is not requested
```
when I do 
```
ReactiveTemplates.set('collectionspostscreate', 'collectionspostscreate');
```
in collections package admin.js I see where the request is being originated. And I think it should be possible to do custom template per collection.

**Comment by nicolaslopezj** [comment]
You are missing the dots
It's
> ReactiveTemplates.set('collections.posts.create', 'myTemplate');
>

**Comment by timfam** [comment]
Sorry it is line 35 in admin.js
```
ReactiveTemplates.request('collectionCreate.' + this.name, Options.get('collectionsDefaultCreateTemplate'));
```
still get same errors
```
Template "collectionCreate.Posts" is not requested
````
 with 
```
ReactiveTemplates.set('collectionCreate.Posts', 'postCreate');
````

**Comment by rwatts3** [comment]
just realized that files are not working either. Is this on the update plan ?

**Comment by nicolaslopezj** [comment]
@timfam It's 
```js
ReactiveTemplates.set('collectionCreate.posts', 'postCreate');
```

@rwatts3 Files are working, but I updated the s3 driver, check the new install instructions https://github.com/Lepozepo/S3

**Comment by timfam** [comment]
Files work. I got it working. You must setup CORS in aws

**Comment by timfam** [comment]
Perhaps we should place a help note in aws config page pointing to https://github.com/Lepozepo/S3 ?

**Comment by nicolaslopezj** [comment]
Hm, its a really good idea but it can't be implemented right now

**Comment by timfam** [comment]
Tried different possible combinations including
```
ReactiveTemplates.set('collectionCreate.posts', 'postCreate');
```
no luck

**Comment by nicolaslopezj** [comment]
For me its working with

```js
ReactiveTemplates.set('collectionCreate.posts', 'myTemplate')
```

To see the available templates call this

```js
ReactiveTemplates._templates
```

**Comment by rwatts3** [comment]
Files work however you can't browse the file directory like in old Orion.

**Comment by timfam** [comment]
That is different package from s3

**Comment by nicolaslopezj** [comment]
Exactly. I don't know if that is going to be in v1.0. What do you think?

**Comment by timfam** [comment]
Leave it out for now. There are other ways of viewing image data

**Comment by rwatts3** [comment]
Ok.

**Comment by rwatts3** [comment]
So I spent all night working on pages.  And had horrible luck.  I thought about reimplementing pages.  Create a collection called pages with a slug , a hasOne relationship for templates and and some how add the option to config to define templates you have already created.  I need thoughts and help on the rest and logic.

**Comment by timfam** [comment]
I see my template now. i think the mistake was putting it in /both folder. It should be clientside only? 

```

**Comment by rwatts3** [comment]
Right

**Comment by timfam** [comment]
I will help out with pages later today, you cant rush that package, it has a few moving parts

**Comment by mraak** [comment]
Hi all, I haven't checked in in a while, was waiting for roles, but seems that plan got scrapped. I also see example-blog has a v.01 branch, but how to actually make it run with v.01 branch core?

**Comment by timfam** [comment]
everything is in there just download and run

**Pull request merged**
