### PR TITLE
Multiple apps, one DB

### PR DESCRIPTION
**Pull request by jorisroling**
To allow multiple app, accessing the same DB, the singular **config** & **dictionary** entries in OrionJS won't do. In our case every app deploy has it's own URL, and therefor all kinds of services (like **facebook** and what's not...), have theyr own setup (config) requirements.

To allow for such a setup, this simple patch works. It has every participating app it's own ENV variable (ORION_APPID). If this ENV variable is set, it is used as key (_id) for **config** and  **dictionary** lookups (server only). 

Works for us...

### CODE REVIEW

**Comment by jorisroling** [comment]
Ah, I forgot to mention, is completely *backward* compatible, everything is as it was when no ORION_APPID is provided.

**Comment by nicolaslopezj** [comment]
And if I set the same ORION_APPID to use the same config and dictionary, it works?

**Comment by jorisroling** [comment]
Yes, that is, NOT setting ORION_APPID will have Orion behave as it was, setting it, say to 'beta', will have Orion search for a dictionary with _id 'beta' and config with _id 'beta'.

**Comment by nicolaslopezj** [comment]
Great!

**Pull request merged**
