### PR TITLE
Package Enhancements

### PR DESCRIPTION
**Pull request by ryanbuiltthat**
#### Added Configuration Settings
- Froala activation key
- Froala editor height
- S3 editable path, *defaults to orionjs*

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
Good! Thanks

**Comment by nicolaslopezj** [comment]
I changed config to options, but setting height doesn't work (options is working correctly)

**Comment by ryanbuiltthat** [comment]
I'm nor sure I follow. So the height didn't work when changed to an option or it didn't work even when a config setting? I'll updatey fork and see, I had that thing hummin' yesterday

**Comment by nicolaslopezj** [comment]
Hm, maybe it worked with config but it needs to be done with options

**Comment by ryanbuiltthat** [comment]
In froala.js the `minHeight` needs to be changed to `height`

https://www.froala.com/wysiwyg-editor/docs/options#height

**Comment by nicolaslopezj** [comment]
But that makes froala height static, and we don't want that right?

**Comment by ryanbuiltthat** [comment]
I never even considered a rich text editor should be as responsive as we can make it. You're right itd lock you in to a height. Your minHeight should have worked. I can take a look at this this evening and get it sorted

**Comment by ryanbuiltthat** [comment]
I see that when you set a default value in your option, froala responds to that. I can't see though where the option is specified. Is it in the template?

**Comment by nicolaslopezj** [comment]
Its here https://github.com/orionjs/orion/blob/master/packages/froala/froala.js#L10

**Pull request merged**
