### PR TITLE
Version 1.7

### PR DESCRIPTION
**Pull request by nicolaslopezj**
Orion v1.7 will come with the following new features:

- [x] ```updatedBy``` attribute by @ojread #338.
- [x] Rewrite relationships attribute.
- [x] Add mongodb indexes to ```createdAt```, ```createdBy```, ```updateAt```, ```updateBy``` attributes.
- [x] Add option to order by orion attributes in tabular.
- [x] Save state in all tabular tables.
- [x] Fix hasOne attribute column with multiple title fields.
- [x] Better permissions for editing roles.

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
@rwatts3 Yes it does

**Comment by rwatts3** [comment]
Nice ! thanks man.

**Comment by rwatts3** [comment]
I'll close the issue.

**Comment by rwatts3** [comment]
What's your planned ETA ? 
Great things you are bringing to the table btw .

**Comment by nicolaslopezj** [comment]
The checked items are ready, I'm just waiting if there are any new features or bug fixes in a short time.

**Comment by rwatts3** [comment]
I was looking to extend Orion a little further with a tray at the bottom of the admin area similar to this http://screencast.com/t/Ah8HTH3M

Do you think you could add an empty ReactiveTemplate at the bottom of the admin layout. So that anyone could request it and add what ever template they want. It could just be empty nothing you'd have to put there for now. 

something like 

```html
{{> reactiveTemplate template=extra }}

or

{{> reactiveTemplate template=custom}}
```

**Comment by nicolaslopezj** [comment]
You can just replace the layout template and add it. It should be very easy.

**Pull request merged**
