### PR TITLE
Use tabular for /admin/accounts

### PR DESCRIPTION
**Pull request by frabrunelle**
I modified the accounts package (as well as the bootstrap and materialize packages) to show the list of Meteor.users (/admin/accounts) using tabular.

In the application I am building, there will be thousands of users and admins need to be able to find users quickly (e.g. by typing their name in a search box).

I also wanted to be able to easily override the columns that are displayed.

This is now possible by changing the value of `orion.accounts.tabular.options.columns`.

For example, I would write this if I wanted to remove the "name" column:

```javascript
orion.accounts.tabular.options.columns = [
  {
    data: 'emails',
    title: i18n('accounts.index.tableTitles.email'),
    render: function(emails) {
      return emails.map(function(email) {
        return email.address;
      }).join(', ');
    }
  },
  {
    title: i18n('accounts.index.tableTitles.enrolled'),
    tmpl: Meteor.isClient && Template[ReactiveTemplates.get('accounts.index.enrolled')]
  },
  {
    data: 'roles()',
    title: i18n('accounts.index.tableTitles.roles'),
    render: function(roles) {
      var labels = roles.map(function(role) {
        return '<span class="label label-danger">' + role + '</span>';
      });
      return labels.join(' ');
    }
  },
  {
    title: i18n('accounts.index.tableTitles.actions'),
    tmpl: Meteor.isClient && Template[ReactiveTemplates.get('accounts.index.buttons')]
  }
];
```

### CODE REVIEW

**Comment by frabrunelle** [comment]
Does anyone have any feedback? Thanks.

**Comment by nicolaslopezj** [comment]
Sorry @PEM--, I haven't had time to review. This will go in the next version of orion.

**Comment by PEM--** [comment]
You mean @frabrunelle :wink:

**Comment by nicolaslopezj** [comment]
Oh sorry, I mean @frabrunelle

**Comment by frabrunelle** [comment]
:+1: 

Sounds good!

**Comment by frabrunelle** [comment]
I have to make another PR so I will close this one and make a new one which will be based on another branch (instead of master).

**Pull request closed without merging**
