### PR TITLE
simplify Chinese language package for v1.1

### PR DESCRIPTION
**Pull request by xi3**
simplify Chinese language package for v1.1

### CODE REVIEW

**Comment by timfam** [comment]
Thanks for the package @nicolaslopezj  will review it

**Comment by nicolaslopezj** [comment]
Thanks a lot for the PR.

But we have some errors. Please use the structure used in https://github.com/orionjs/orion/blob/v1.1/packages/lang-en/en.js because the one you are using is the old.

**Comment by xi3** [comment]
I am a newer. May be a short guide for contribution and testing helps a lot.

**Comment by nicolaslopezj** [comment]
Translate this gist. https://gist.github.com/nicolaslopezj/12802f6d80dc2385d9d4.
You can publish another gist with Chinese lang or make another pr.

Thanks!

**Pull request closed without merging**
