### PR TITLE
first iteration after issue#8

### PR DESCRIPTION
**Pull request by lc3t35**
Please give it a try :)

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
This is great.
Don't you prefer to have this package as yours ```lc3t35:orion-local-filesytem```?

**Comment by timfam** [comment]
@lc3t35 contrib should be under maintainer names, after much reviews and if down the road community vote to bring into core, then we can make so. Good job!

**Comment by lc3t35** [comment]
Done : https://github.com/lc3t35/filesystem-local

**Comment by nicolaslopezj** [comment]
Excellent!

**Comment by rwatts3** [comment]
Just installed locally , should there be routes for /thumbs/ image loads but doesn't display in example-blog.

**Comment by timfam** [comment]
this queue should be closed and all issue moved to https://github.com/lc3t35/orion-filesystem-local/issues

**Comment by loongmxbt** [comment]
Just for customization not a released package: https://github.com/loongmxbt/orion-lfs
Can really delete file from local server.

**Pull request closed without merging**
