### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by PEM--**

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
Thanks pem.

Can you publish this as yours? I can't maintain your package because I don't know French

**Comment by nicolaslopezj** [comment]
https://github.com/orionjs/examples/blob/master/language/README.md

**Comment by PEM--** [comment]
OK, no pb. Doing it right now.

**Comment by PEM--** [comment]
Done with the update on the README as well.

**Comment by nicolaslopezj** [comment]
Great!

**Pull request closed without merging**
