### PR TITLE
change from 'en' to 'es'

### PR DESCRIPTION
**Pull request by TedEwanchyna**
the default language is Spanish and it should be English

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
The default language is English and it's installed on every distribution automatically. This package is optional and adds the Spanish translations

**Comment by TedEwanchyna** [comment]
I understand that it may be optional but the file is included when I do a git clone.
I am following the tutorial at  http://orionjs.org/tutorials/how-to-contribute.

When I add the blog example and then create an account all the admin menus etc are in Spanish which is weird. Then I dug back through the code and found this:

If you look in orionjs/orion/packages:
ted@8540w-U1404lts:~/test/meteor/orionjs/orion/packages$ head -3 lang-en/en.js 
i18n.map('en', {
  global: {
    save: 'Save',
ted@8540w-U1404lts:~/test/meteor/orionjs/orion/packages$ head -3 lang-es/es.js 
i18n.map('en', {
  global: {
    save: 'Guardar',

Do you see that they both have this: i18n.map('en', {   ?
Both have en as the key for i18n.map. When I changed en to es, all my admin was then English.

I don't know how else to explain it. 
It is not a big fix but it is a bug and it is confusing for someone like me just starting with orionjs.

Ted

**Comment by nicolaslopezj** [comment]
Oh! sorry! you are right. I changed by mistaked

**Comment by rwatts3** [comment]
Hey Nick, 

I'm looking into a possibility to change language options within the admin panel, do you have any thoughts as to benefits, and/or detriments to a feature like t his.

**Comment by nicolaslopezj** [comment]
Ryan send me a email to discuss!

**Pull request merged**
