### PR TITLE
Sidebar Improvements (Adds Bootstrap Dropdowns Option)

### PR DESCRIPTION
**Pull request by rwatts3**
Additional Improvements to the Sidebar. 

- Updated the sidebar to use ReactiveTemplates better. 
- Created a new ReactiveTemplate request called **adminSidebar**
- Updated layout.html to use the **adminSidebar** ReactiveTemplate helper. 
- Created Two additional templates **orionBootstrapSidebarDropdown** and **orionBootstrapSidebarDropwonLink**  essentially each of these just mimic the setup of the original bootstrap templates. logic. 

After these updates the user can easily use set the adminSidebar ReactiveTemplate to orionBootstrapSidebarDropdown and it will render the two templates I created. Otherwise if the option is not set it will default to the original sidebar. 

```js
ReactiveTemplates.set('adminSidebar' , 'orionBootstrapSidebarDropdown');
```
> By the way this is a fork of the previous pr #190 . In case you want to choose both updates, or choose the other for now. If both updates are ok I will be happy to remove the previous request.

### CODE REVIEW

**Comment by rwatts3** [comment]
This update takes a section on the sidebar definition allowing the user to assign the section as the title of the dropdown.

**Comment by kevohagan** [comment]
is there any news on this pull request being merged? this seems pretty awesome :)

**Comment by kevohagan** [comment]
@timfam @rwatts3 @nicolaslopezj i would love to see this :)

**Comment by timfam** [comment]
It will merged into v1.2 coming out soon

**Comment by kevohagan** [comment]
where is this at? any documentation on this @rwatts3 @timfam ? thanks for the help! :)

**Comment by rwatts3** [comment]
Good day ,

I submitted the PR a while back.  It was closed and 1.2 was written.  No
documentation on whether it was added or not.

On Friday, July 24, 2015, kevohagan <notifications@github.com> wrote:

> where is this at? any documentation on this @rwatts3
> <https://github.com/rwatts3> @timfam <https://github.com/timfam> ? thanks
> for the help! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/pull/200#issuecomment-124560904>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by kevohagan** [comment]
Thanks Ryan, yeah ive looked at source code and your PR doesnt seem to have
been merged :(

**Comment by rwatts3** [comment]
No problem sorry it didn't help.

On Friday, July 24, 2015, kevohagan <notifications@github.com> wrote:

> Thanks Ryan, yeah ive looked at source code and your PR doesnt seem to have
> been merged :(
>
> On Fri, Jul 24, 2015 at 5:39 PM Ryan Watts <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Good day ,
> >
> > I submitted the PR a while back. It was closed and 1.2 was written. No
> > documentation on whether it was added or not.
> >
> > On Friday, July 24, 2015, kevohagan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > where is this at? any documentation on this @rwatts3
> > > <https://github.com/rwatts3> @timfam <https://github.com/timfam> ?
> > thanks
> > > for the help! :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/orionjs/orion/pull/200#issuecomment-124560904>.
> > >
> >
> >
> > --
> > Ryan Watts
> > E.ryandwatts@gmail.com
> <javascript:_e(%7B%7D,'cvml','E.ryandwatts@gmail.com');>
> > C.520-442-8962
> > F.520-437-0914
> > IN. https://www.linkedin.com/in/ryandwatts
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/orionjs/orion/pull/200#issuecomment-124561336>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/pull/200#issuecomment-124562917>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Pull request closed without merging**
