### PR TITLE
Sidebar improvements

### PR DESCRIPTION
**Pull request by rwatts3**
## Updates to Sidebar Sections

These updates now allows the sidebar sections to be dynamic. 
- Updated `layout.js` to add a adminSections helper that creates an array based on sections that have been passed to a link when creating a collection. 
- Updated both Bootstrap and Materialize theme to use the dynamic sections, rather than hardcoding each section. 
- Sections are returned by alphabetical order, so I updated the section assignments by setting bottom to zBottom ensuring it is always last , and setting top "where the dictionary is placed" to aTop. 
- Updates also respect numbers so if you want an item to come first then put 1 before the item name as you would do with links.

### CODE REVIEW

**Comment by rwatts3** [comment]
Status update on this PR ?

**Comment by nicolaslopezj** [comment]
This will go in 1.2

**Comment by rwatts3** [comment]
Thank you

**Comment by rwatts3** [comment]
We could close this one if you'd like all updates are in the other PR.

**Comment by rwatts3** [comment]
Was this added to 1.2 ?

**Comment by nicolaslopezj** [comment]
Its in process

**Comment by rwatts3** [comment]
Let me know if you have any questions or if I can help integrate

**Pull request closed without merging**
