### PR TITLE
Image attribute

### PR DESCRIPTION
**Pull request by nicolaslopezj**
Image attribute with the following features:

- Force ratio
- Preview
- Multiple sizes
- Effects
- Cut images

Will use:
- [jonblum:jquery-cropper](http://fengyuanchen.github.io/cropper/) to crop images

### CODE REVIEW

**Comment by timfam** [comment]
What about automatic image resize or using something like imagemagick?

**Comment by kevohagan** [comment]
Maybe cfs and cfs-s3 might be an option here.

**Comment by nicolaslopezj** [comment]
All the image manipulation must be done client side.
image-attribute must work with any filesystem provider

**Comment by nicolaslopezj** [comment]
This will be included in v1.1

**Pull request closed without merging**
